### ISSUE TITLE
How to selfhost this project?

### ISSUE THREAD

**Issue by android116** [AlejandroAkbal/Image-to-Text-OCR#1]
Can this project be hosted on my local Linux server? If so, is it possible to get instructions on how to do this?

**Comment by AlejandroAkbal** [comment]
For sure, just run a webserver in front of it and it will work, just need to run `npm run build` to generate the distribution files.

I am using Netlify for hosting this, it's free.

**Comment by android116** [comment]
Happened.
And where is the launch on http://localhost:3000 configured? I would like to change to http://localhost/ocr . Is it possible?

**Comment by android116** [comment]
> For sure, just run a webserver in front of it and it will work, just need to run `npm run build` to generate the distribution files.
> 
> I am using Netlify for hosting this, it's free.

Happened.
And where is the launch on http://localhost:3000/ configured? I would like to change to http://localhost/ocr . Is it possible?

**Comment by AlejandroAkbal** [comment]
Localhost:3000 only happens if you use the 'npm run start' command, which shouldn't be used for production, it's best that you configure a web server like Nginx, there you can put it on localhost/ocr
